#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 12 02:12:35 2019

@author: Barbara Perim
"""

DNA = "CTATCGGCCGGCACGTAGGTCCGGCTCTCTCCCCGTGCCTTTCATTTCTAACGATCATCTTTTTAAAGACAACACGGAGTTGTCCCTGCTGTGTGGAAACCGCGGCACTGGTAGTTTGGTCCGAGATTGCAACAACCTGTCCTAGAAGGCACATTGGTCGGATACAGACCTAGTCAATTAGGGCCAGTTCAGCCGGGTCCGTTTATGGCGGCCTCAACTATGATACTCGAAAAAGTACCTGGGTCGCGCAGCTGGTGGCTCTGGGATCCTGGTTGCATGAGAAACGAGTGAAAGCAGATATGTAATTTTTGTGGTCTTCGTAGGACAGTAAGGTAAAACCCACCACTTCAGCTCGATGCTAGACCGACCGTTTCCTATATATTTCCGTCGAATACTGGGACACAAGCCCTTGCGCAGTTTCGCGGTACTTCTCACGTGGGTTGGCGTTCACCGTGAGACCTCCTTTCGCTGCTACGTGTGATACAAAAGCTCGGTCCGATAACAAATTTTGTGAAGCCGGACCAGTTGCAAGGGGCGATATCCGGCGGGACTGAATGACATAGCGATCTCAGAGCCAATGCTATATTAAAGGATCATTTGATGACTGGGGCGGAGGGAGCAAACTGCTAATACTGTCGGCTGTTTATGTAGACCTTATAATTGCAGCCTCACATATTCTGCTAAGCAGTTATAGTCATTACCAGCAGTTCTAACGGGGCGAGAGGGATATCACGGAAGTAGGAAAAGCTACCCAGTCCGCCTTGGTAAGCATGTACTCTTATTGCTACGAAGGACTACATTCAATTATCCTGTAAGATGGCACTAGGAGGCAAAACTGAT"
DNA = DNA[::-1]
DNA_complement = ""
for nucleotide in DNA:
    if nucleotide == "T":
        DNA_complement+="A"
    if nucleotide == "A":
        DNA_complement+="T"
    if nucleotide == "G":
        DNA_complement+="C"
    if nucleotide == "C":
        DNA_complement+="G"
        
print(DNA_complement)