#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 11 23:02:02 2019

@author: Barbara Perim
"""

def count_nucleotide(dna_string):
    dna_dict = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
    for i in dna_string:
        dna_dict[i]+=1
    [print (i, end=' ') for i in dna_dict.values()]

count_nucleotide("ATGTGTTAAACCCGTAGACTTCTATTATAGGCGGCCTTAGTTATTGTACTGCATTATGTCCCATTAAGTGGGGGTAATTAGAGGCACCCCGTCGTCCGCAGTAGTACAGGCCTCTTGCACCCATATGAACGCGCGAATGGATTCCACACGCAGACCCTTGGTCCGGGATTACGGATGAGTAATTAATCTGTCGTAGGATTAATGCTAAGGTGATAGCCACGACCCCGAAGATCTCGAGCTAACTTCGCCCAAAGGAGATATGGGTCTGAATCGAGTCGGACTGCACCTTACGGACCCCGACGGCGCAGGGGCCCGTTCACAGACGTACAGGGTGCTGAGTTCTGTTTTAAGAGTTCGGAGACTCGGGCGCGATATGGGTCGGGCAAGACACGACTGATGACACAAGACAGGCTGGTATCATTTGGTCATATCCGCAAAGTTGAACGCCGTATTGGCCAAGCGTCGGGACGCGGAGCTGCTCTGGAAGTGGCCCTCTTGAAGCTGAAGGTAAGTGCTTCTCTTCTCGAGATTTCTTTGGTTGGTGAAATTTTTATGTGCGCATGCGCTAGACTCGCTAGAAGGGGAAGGGAACCATTGTTGGTCTGCGAGTAGCCGGCATTTACCGCAGTTGAGCCCGTGATCGCGGATCTATTCATCGGCGTCTAATCGAAGGGTCCATGTAGACAGAATCCCCGAGTGAGGGTGTTCGCATTACAGGACTGAGCCTCGGGTGCAAGCGGGGCAAAATCACGTCGTTCTGCACTCGGCGGGAGTGTACGGGCTTGGGGCGAATGCTGTATTGGCTCTTCAACATAATCTTAGAGCCTGAACGTCGCCGGACGAGCATGAGTTACTTAGACAATCCCAGGAGAACTTCTGTACTCGACCTATCGAGGTTCACACCCA")