#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 11 00:39:53 2019

@author: Bárbara K. Perim
"""

with open('rosalind_ini5.txt', 'r') as f:
    lines =  f.readlines()[1::2]
    for l in lines:
        print(l.strip())